/* Copyright 2012 Mozilla Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
"use strict";
// eslint-disable-next-line no-var
var FontInspector=function(){let e,t=!1;function n(){const e=document.querySelectorAll("span[data-font-name]");for(const t of e)t.className="debuggerHideText"}function a(e,t){const n=document.querySelectorAll(`span[data-font-name=${e}]`);for(const e of n)e.className=t?"debuggerShowText":"debuggerHideText"}function o(e){if(!e.target.dataset.fontName||"SPAN"!==e.target.tagName.toUpperCase())return;const t=e.target.dataset.fontName,n=document.getElementsByTagName("input");for(let e=0;e<n.length;++e){const o="n[e];o.dataset.fontName===t&amp;&amp;(o.checked=!o.checked,a(t,o.checked),o.scrollIntoView())}}return{" properties="" functions="" needed="" by="" pdfbug.="" id:"fontinspector",name:"font="" inspector",panel:null,manager:null,init:function(t){const="" a="this.panel,o=document.createElement(&quot;button&quot;);o.addEventListener(&quot;click&quot;,n),o.textContent=&quot;Refresh&quot;,a.appendChild(o),e=document.createElement(&quot;div&quot;),a.appendChild(e)},cleanup:function(){e.textContent=&quot;&quot;},enabled:!1,get" active(){return="" t},set="" active(e){t="e,t?(document.body.addEventListener(&quot;click&quot;,o,!0),n()):(document.body.removeEventListener(&quot;click&quot;,o,!0),function(){const" e="document.querySelectorAll(&quot;span[data-font-name]&quot;);for(const" t="" of="" e)t.classname="" }())},="" fontinspector="" specific="" functions.="" fontadded:function(t,o){const="" i="function(e,t){const" n="document.createElement(&quot;table&quot;);for(let" s="document.createElement(&quot;td&quot;);s.textContent=e[t[a]].toString(),o.appendChild(s),n.appendChild(o)}return" n}(t,["name","type"]),s="t.loadedName,d=document.createElement(&quot;div&quot;),l=document.createElement(&quot;span&quot;);l.textContent=s;const" r="document.createElement(&quot;a&quot;);o?(o=/url\(['&quot;]?([^)&quot;']+)/.exec(o),r.href=o[1]):t.data&amp;&amp;(r.href=URL.createObjectURL(new" blob([t.data],{type:t.mimetype}))),r.textcontent="Download" ;const="" c="document.createElement(&quot;a&quot;);c.href=&quot;&quot;,c.textContent=&quot;Log&quot;,c.addEventListener(&quot;click&quot;,(function(e){e.preventDefault(),console.log(t)}));const" p="document.createElement(&quot;input&quot;);p.setAttribute(&quot;type&quot;,&quot;checkbox&quot;),p.dataset.fontName=s,p.addEventListener(&quot;click&quot;,(function(){a(s,p.checked)})),d.appendChild(p),d.appendChild(l),d.appendChild(document.createTextNode(&quot;" ")),d.appendchild(r),d.appendchild(document.createtextnode("="" ")),d.appendchild(c),d.appendchild(i),e.appendchild(d),="" somewhat="" hack,="" should="" probably="" add="" hook="" for="" when="" the="" text="" layer="" is="" done="" rendering.="" settimeout(()="">{this.active&amp;&amp;n()},2e3)}}}();let opMap;
// Manages all the page steppers.

// eslint-disable-next-line no-var
var StepperManager=function(){let e=[],t=null,n=null,a=null,o=Object.create(null);return{
// Properties/functions needed by PDFBug.
id:"Stepper",name:"Stepper",panel:null,manager:null,init:function(e){const i=this;n=document.createElement("div"),a=document.createElement("select"),a.addEventListener("change",(function(e){i.selectStepper(this.value)})),n.appendChild(a),t=document.createElement("div"),this.panel.appendChild(n),this.panel.appendChild(t),sessionStorage.getItem("pdfjsBreakPoints")&amp;&amp;(o=JSON.parse(sessionStorage.getItem("pdfjsBreakPoints"))),opMap=Object.create(null);for(const t in e.OPS)opMap[e.OPS[t]]=t},cleanup:function(){a.textContent="",t.textContent="",e=[]},enabled:!1,active:!1,
// Stepper specific functions.
create:function(n){const i=document.createElement("div");i.id="stepper"+n,i.hidden=!0,i.className="stepper",t.appendChild(i);const s=document.createElement("option");s.textContent="Page "+(n+1),s.value=n,a.appendChild(s);const d=o[n]||[],l=new Stepper(i,n,d);return e.push(l),1===e.length&amp;&amp;this.selectStepper(n,!1),l},selectStepper:function(t,n){let o;for(t|=0,n&amp;&amp;this.manager.selectPanel(this),o=0;o<e.length;++o){const n="e[o];n.panel.hidden=n.pageIndex!==t}const" i="a.options;for(o=0;o<i.length;++o){const" e="i[o];e.selected=(0|e.value)===t}},saveBreakPoints:function(e,t){o[e]=t,sessionStorage.setItem(&quot;pdfjsBreakPoints&quot;,JSON.stringify(o))}}}();" the="" stepper="" for="" each="" page's="" operatorlist.="" const="" shorter="" way="" to="" create="" element="" and="" optionally="" set="" textcontent.="" function="" e(e,t){const="" t&&(n.textcontent="t),n}function" t(e){if("string"="=typeof" e){const="" t="75;return" e.length<="t?e:e.substring(0,t)+&quot;...&quot;}if(&quot;object&quot;!=typeof" e||null="==e)return" e;if("length"in="" e){="" array="" o,i;for(o="0,i=Math.min(n,e.length);o<i;o++)a.push(t(e[o]));return" o<e.length&&a.push("..."),a}const="" a="" in="" e)n[a]="t(e[a]);return" n}="" eslint-disable-next-line="" no-shadow="" return="" class{constructor(e,t,n){this.panel="e,this.breakPoint=0,this.nextBreakPoint=null,this.pageIndex=t,this.breakPoints=n,this.currentIdx=-1,this.operatorListIdx=0}init(t){const" s="step&quot;),o=e(&quot;table&quot;);a.appendChild(o),o.cellSpacing=0;const" o(){const="">15e3)return;const i=document.createDocumentFragment(),s=Math.min(15e3,n.fnArray.length);for(let a=this.operatorListIdx;a<s;a++){const s="e(&quot;tr&quot;);s.className=&quot;line&quot;,s.dataset.idx=a,i.appendChild(s);const" d="this.breakPoints.includes(a),l=n.argsArray[a]||[],r=e(&quot;td&quot;),c=e(&quot;input&quot;);c.type=&quot;checkbox&quot;,c.className=&quot;points&quot;,c.checked=d,c.dataset.idx=a,c.onclick=o,r.appendChild(c),s.appendChild(r),s.appendChild(e(&quot;td&quot;,a.toString()));const" p="opMap[n.fnArray[a]];let" h="l;if(&quot;showText&quot;===p){const" t="l[0],n=e(&quot;tr&quot;),a=e(&quot;tr&quot;),o=e(&quot;tr&quot;);for(let" i="0;i<t.length;i++){const" s&&null!="=s)n.appendChild(e(&quot;td&quot;,s.originalCharCode)),a.appendChild(e(&quot;td&quot;,s.fontChar)),o.appendChild(e(&quot;td&quot;,s.unicode));else{" null="" or="" number="" const="" instanceof="" htmlelement?s.appendchild(h):s.appendchild(e("td",json.stringify(t(h))))}if(s<n.fnarray.length){const="" e-t}));for(let="" e="0;e<this.breakPoints.length;e++)if(this.breakPoints[e]">this.currentIdx)return this.breakPoints[e];return null}breakIt(e,t){StepperManager.selectStepper(this.pageIndex,!0),this.currentIdx=e;const n=e=&gt;{switch(e.keyCode){case 83:// step
document.removeEventListener("keydown",n),this.nextBreakPoint=this.currentIdx+1,this.goTo(-1),t();break;case 67:// continue
document.removeEventListener("keydown",n),this.nextBreakPoint=this.getNextBreakPoint(),this.goTo(-1),t()}};document.addEventListener("keydown",n),this.goTo(e)}goTo(e){const t=this.panel.getElementsByClassName("line");for(let n=0,a=t.length;n</s;a++){const></e.length;++o){const></n.length;++e){const>